//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadFilePlan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Download {
            get {
                return ((bool)(this["Download"]));
            }
            set {
                this["Download"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoEncrypt {
            get {
                return ((bool)(this["DoEncrypt"]));
            }
            set {
                this["DoEncrypt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int LogEvery {
            get {
                return ((int)(this["LogEvery"]));
            }
            set {
                this["LogEvery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RefreshAuthTokenEveryXMinutes {
            get {
                return ((int)(this["RefreshAuthTokenEveryXMinutes"]));
            }
            set {
                this["RefreshAuthTokenEveryXMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxThreads {
            get {
                return ((int)(this["MaxThreads"]));
            }
            set {
                this["MaxThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\zWork\\Export\\Reports")]
        public string CsvOutput {
            get {
                return ((string)(this["CsvOutput"]));
            }
            set {
                this["CsvOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\zWork\\Export\\Downloaded_Items")]
        public string FilesOutput {
            get {
                return ((string)(this["FilesOutput"]));
            }
            set {
                this["FilesOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Permissions,Categories")]
        public string ValuesToRetrieve {
            get {
                return ((string)(this["ValuesToRetrieve"]));
            }
            set {
                this["ValuesToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int MaxItemsPerFolder {
            get {
                return ((int)(this["MaxItemsPerFolder"]));
            }
            set {
                this["MaxItemsPerFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".files, _files, -Dateien, _fichiers, _bestanden, _file, _archivost, -filer, _tied" +
            "ostot, _pliki, _soubory, _elemei, _ficheiros, _arquivos, _dosyalar, _datoteke, _" +
            "fitxers, _failid, _fails, _bylos, _fajlovi, _fitxategiak")]
        public string BlockedExtensions {
            get {
                return ((string)(this["BlockedExtensions"]));
            }
            set {
                this["BlockedExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string ZipPassword {
            get {
                return ((string)(this["ZipPassword"]));
            }
            set {
                this["ZipPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./AES.key")]
        public string AES_key {
            get {
                return ((string)(this["AES_key"]));
            }
            set {
                this["AES_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string OTCS_Secret {
            get {
                return ((string)(this["OTCS_Secret"]));
            }
            set {
                this["OTCS_Secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin")]
        public string OTCS_Username {
            get {
                return ((string)(this["OTCS_Username"]));
            }
            set {
                this["OTCS_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("otcs_password")]
        public string SecureOTCSPassword_FileName {
            get {
                return ((string)(this["SecureOTCSPassword_FileName"]));
            }
            set {
                this["SecureOTCSPassword_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("otcs_username")]
        public string SecureOTCSUsername_FileName {
            get {
                return ((string)(this["SecureOTCSUsername_FileName"]));
            }
            set {
                this["SecureOTCSUsername_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSecureCredentials {
            get {
                return ((bool)(this["UseSecureCredentials"]));
            }
            set {
                this["UseSecureCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string DB_Secret {
            get {
                return ((string)(this["DB_Secret"]));
            }
            set {
                this["DB_Secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string DB_Username {
            get {
                return ((string)(this["DB_Username"]));
            }
            set {
                this["DB_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csdb_secret")]
        public string SecureCSDBSecret_Filename {
            get {
                return ((string)(this["SecureCSDBSecret_Filename"]));
            }
            set {
                this["SecureCSDBSecret_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csdb_username")]
        public string SecureCSDBUsername_Filename {
            get {
                return ((string)(this["SecureCSDBUsername_Filename"]));
            }
            set {
                this["SecureCSDBUsername_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AES.key")]
        public string SecureAESKey_Filename {
            get {
                return ((string)(this["SecureAESKey_Filename"]));
            }
            set {
                this["SecureAESKey_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("243")]
        public int PathMinLength {
            get {
                return ((int)(this["PathMinLength"]));
            }
            set {
                this["PathMinLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int PathMaxLength {
            get {
                return ((int)(this["PathMaxLength"]));
            }
            set {
                this["PathMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_vti_")]
        public string BlockedStartWith {
            get {
                return ((string)(this["BlockedStartWith"]));
            }
            set {
                this["BlockedStartWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\t")]
        public string LongFilePathLocation {
            get {
                return ((string)(this["LongFilePathLocation"]));
            }
            set {
                this["LongFilePathLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("site/swiftx/")]
        public string DestPath {
            get {
                return ((string)(this["DestPath"]));
            }
            set {
                this["DestPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsingContainsLogic {
            get {
                return ((bool)(this["UsingContainsLogic"]));
            }
            set {
                this["UsingContainsLogic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\l")]
        public string SPOLongFilePathLocation {
            get {
                return ((string)(this["SPOLongFilePathLocation"]));
            }
            set {
                this["SPOLongFilePathLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4707")]
        public long TargetedNode {
            get {
                return ((long)(this["TargetedNode"]));
            }
            set {
                this["TargetedNode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.51")]
        public string DBSource {
            get {
                return ((string)(this["DBSource"]));
            }
            set {
                this["DBSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.51/otcs/llisapi.dll/api/")]
        public string APIUrl {
            get {
                return ((string)(this["APIUrl"]));
            }
            set {
                this["APIUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OTCS")]
        public string DBCatalog {
            get {
                return ((string)(this["DBCatalog"]));
            }
            set {
                this["DBCatalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.51:8080/otdsws/rest/")]
        public string OTDSApiURL {
            get {
                return ((string)(this["OTDSApiURL"]));
            }
            set {
                this["OTDSApiURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.51/otcs/cs.exe/app/nodes/{0}")]
        public string SourceUrl {
            get {
                return ((string)(this["SourceUrl"]));
            }
            set {
                this["SourceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\RGTX\\Documents\\DownloadFilePlan-ExtractCategory-Faay\\credentials")]
        public string SecureCredentialsPath {
            get {
                return ((string)(this["SecureCredentialsPath"]));
            }
            set {
                this["SecureCredentialsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/sites/ssg-test/")]
        public string SharePointURL {
            get {
                return ((string)(this["SharePointURL"]));
            }
            set {
                this["SharePointURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExtractTargetedNode {
            get {
                return ((bool)(this["ExtractTargetedNode"]));
            }
            set {
                this["ExtractTargetedNode"] = value;
            }
        }
    }
}
